CXXFLAGS=-Wall -g

# clean:

all: Georgio

Georgio:
	@echo "            ** '' "
	@echo "              I "
	@echo "            -----" 
	@echo "             --- "
	@echo '---Delete old content........'
	rm -f ex1
	@echo
	@echo 'Compiling "C" program'
	make ex1
	@echo
	@echo '----Execute my program!!!!!!!!!!'
	@echo
	./ex1
	@echo
	@echo "----End of program --- Giovanni Giorgio"
	@echo
