print("Cálculo de área para triangulo reto!")
l1 = float(input("Informe o lado menor do triangulo? "))
l2 = float(input("Informe o segundo lado menor do tirangulo?"))
print("Sua área total é de", l1 * l2 / 2, "metros.")
print("-----------|------------|-------------")
print("Cálculo de área do quadrado!")
q1= float(input("Insira a medida de um dos lados em metro"))
print("A área do quadrado é de", q1 ** 2, "metros.")
print("-----------|------------|-------------")
print("Cálculo de área do retangulo!")
ret1 = float(input("Por favor, informe a medida em metros do lado menor:"))
ret2 = float(input("Por favor, insira a medida em metros do lado maior:"))
print("A área do retangulo é de", ret1 * ret2, "metros.")
exit()

